server {
		listen 80;
		server_name relay-analytics-holesky.ultrasound.money relay-analytics-hoodi.ultrasound.money;

		location = / {
				return 301 https://github.com/ultrasoundmoney/docs;
		}
}

# RPC endpoints - accept bundle submissions
server {
		listen 80;
		server_name rpc-eu.ultrasound.money rpc-eu-hoodi.ultrasound.money;

		location / {
				default_type application/json;
				return 202 '{"result":202,"error":null}';
		}
}

server {
		listen 80;
		server_name rpc-jp-hoodi.ultrasound.money;

		location / {
				mirror /forward_to_rbx;
				mirror_request_body on;

				default_type application/json;
				return 202 '{"result":202,"error":null}';
		}

		location = /forward_to_rbx {
				internal;
				proxy_pass https://rpc-eu-hoodi.ultrasound.money$request_uri;
				proxy_set_header Host rpc-eu-hoodi.ultrasound.money;
				proxy_set_header X-Origin-Geo "tyo";
				proxy_set_header X-Received-At-Ms $msec;
				proxy_ssl_server_name on;
		}
}

server {
		listen 80;
		server_name *.ultrasound.money;

		location = /eth/v1/builder/status {
				return 200;
		}
}
